# ogolne
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.projectKey=waskok_budget-app
sonar.organization=waskok
sonar.host.url=https://sonarcloud.io

# backend i frontend
sonar.modules=backend,frontend

# backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main
backend.sonar.java.binaries=target/classes

# frontend bez testow
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/*.test.tsx,**/__tests__/**