spring.application.name=PASIR_Wasko_Klaudiusz
spring.config.import=optional:file:.env[.properties]

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE:wasko_klaudiusz_k05_spring}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user-wk}
spring.datasource.password=${MYSQL_PASSWORD:zaq12wsx}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls

app.jwt.secret=${JWT_SECRET}